#!/bin/bash
PATH="$PWD/node_modules/.bin":$PATH

hello() {
    echo Hello from taskfile
    echo args: "$1" "$2" "$3"
}

remark_run() {
    remark readme.md --use toc --use license "$@"
}

remark_output() {
    remark_run --output
}

build() {
    rm -rf dist
    cp -rf src dist && /usr/bin/find dist -name '*.spec.ts' | xargs rm -f
    cd dist
    tsc index.ts --importHelpers --target es2015 --module commonjs --sourceMap true --skipLibCheck true --declaration true
    cd ..
    cp README.md LICENSE package.json dist
}

eslint_run() {
    eslint src --ext ts
}

eslint_watch() {
    eslint_run
    inotifywait_cmd=`watch_cmd`
    while true; do
        $inotifywait_cmd -r src && \
            eslint_run
    done
}

watch_cmd() {
    case `uname -o` in
        Linux)
            echo 'inotifywait'
        ;;
        Msys)
            echo 'inotifywait-win32.cmd'
        ;;
        *)
            echo 'inotifywait'
        ;;
    esac
}

"$@"
